[project]
name = "tides"
version = "0.1.0"
description = "show tides during daylight for various locations"
readme = "README.md"
requires-python = "~=3.12.0"
dependencies = [
    "beautifulsoup4~=4.13.4",
    "flask~=3.1.1",
    "gunicorn~=23.0.0",
    "pytz>=2025.2",
]
